feat(openvpn): add server setup support

diff --git a/roles/networking/openvpn/templates/init.d_openvpn.j2 b/roles/networking/openvpn/templates/init.d_openvpn.j2
--- a/roles/networking/openvpn/templates/init.d_openvpn.j2
+++ b/roles/networking/openvpn/templates/init.d_openvpn.j2
@@ -61,8 +61,10 @@ start_vpn () {
       STATUSARG=""
     else
       # prepare default status file
-      STATUSARG="--status /var/run/openvpn.$NAME.status $STATUSREFRESH"
+      STATUSARG="--status /run/openvpn/$NAME.status $STATUSREFRESH"
     fi
+
+    mkdir -p /run/openvpn
 
     # tun using the "subnet" topology confuses the routing code that wrongly
     # emits ICMP redirects for client to client communications
@@ -92,12 +94,12 @@ start_vpn () {
 
     STATUS=0
     start-stop-daemon --start --quiet --oknodo \
-        --pidfile /var/run/openvpn.$NAME.pid \
-        --exec $DAEMON -- $OPTARGS --writepid /var/run/openvpn.$NAME.pid \
+        --pidfile /run/openvpn/$NAME.pid \
+        --exec $DAEMON -- $OPTARGS --writepid /run/openvpn/$NAME.pid \
         $DAEMONARG $STATUSARG --cd $CONFIG_DIR \
         --config $CONFIG_DIR/$NAME.conf $script_security < /dev/null || STATUS=1
 
-    [ "$OMIT_SENDSIGS" -ne 1 ] || ln -s /var/run/openvpn.$NAME.pid /run/sendsigs.omit.d/openvpn.$NAME.pid
+    [ "$OMIT_SENDSIGS" -ne 1 ] || ln -s /run/openvpn/$NAME.pid /run/sendsigs.omit.d/openvpn.$NAME.pid
 
     # Set the back the original default value of send_redirects if it was changed
     if [ "$SAVED_DEFAULT_SEND_REDIRECTS" -ne 0 ]; then
@@ -105,11 +107,16 @@ start_vpn () {
     fi
 }
 stop_vpn () {
-  kill `cat $PIDFILE` || true
-  rm -f $PIDFILE
-  [ "$OMIT_SENDSIGS" -ne 1 ] || rm -f /run/sendsigs.omit.d/openvpn.$NAME.pid
-  rm -f /var/run/openvpn.$NAME.status 2> /dev/null
-  log_end_msg 0
+  start-stop-daemon --stop --quiet --oknodo \
+      --pidfile $PIDFILE --exec $DAEMON --retry 5
+  if [ "$?" -eq 0 ]; then
+    rm -f $PIDFILE
+    [ "$OMIT_SENDSIGS" -ne 1 ] || rm -f /run/sendsigs.omit.d/openvpn.$NAME.pid
+    rm -f /run/openvpn/$NAME.status 2> /dev/null
+    log_end_msg 0
+  else
+    log_failure_msg "  Unable to stop VPN '$NAME'"
+  fi
 }
 
 case "$1" in
@@ -161,9 +168,8 @@ start)
 stop)
   log_action_begin_msg "Stopping $DESC"
   if test -z "$2" ; then
-    PIDFILE=
-    for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
-      NAME=`echo $PIDFILE | cut -c18-`
+    for PIDFILE in `ls /run/openvpn/*.pid 2> /dev/null`; do
+      NAME=`echo $PIDFILE | cut -c14-`
       NAME=${NAME%%.pid}
       log_daemon_msg "  Stopping VPN '$NAME'"
       stop_vpn
@@ -174,10 +180,10 @@ stop)
   else
     while shift ; do
       [ -z "$1" ] && break
-      if test -e /var/run/openvpn.$1.pid ; then
+      if test -e /run/openvpn/$1.pid ; then
         log_daemon_msg "  Stopping VPN '$1'"
-        PIDFILE=`ls /var/run/openvpn.$1.pid 2> /dev/null`
-        NAME=`echo $PIDFILE | cut -c18-`
+        PIDFILE=`ls /run/openvpn/$1.pid 2> /dev/null`
+        NAME=`echo $PIDFILE | cut -c14-`
         NAME=${NAME%%.pid}
         stop_vpn
       else
@@ -189,15 +195,13 @@ stop)
 # Only 'reload' running VPNs. New ones will only start with 'start' or 'restart'.
 reload|force-reload)
   log_action_begin_msg "Reloading $DESC"
-  PIDFILE=
-  for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
-    NAME=`echo $PIDFILE | cut -c18-`
+  for PIDFILE in `ls /run/openvpn/*.pid 2> /dev/null`; do
+    NAME=`echo $PIDFILE | cut -c14-`
     NAME=${NAME%%.pid}
 # If openvpn if running under a different user than root we'll need to restart
     if egrep '^[[:blank:]]*user[[:blank:]]' $CONFIG_DIR/$NAME.conf > /dev/null 2>&1 ; then
       log_daemon_msg "  Stopping VPN '$NAME'"
       stop_vpn
-      sleep 1
       log_daemon_msg "  Restarting VPN '$NAME'"
       start_vpn
     else
@@ -213,9 +217,8 @@ reload|force-reload)
 # Only 'soft-restart' running VPNs. New ones will only start with 'start' or 'restart'.
 soft-restart)
   log_action_begin_msg "Soft-restarting $DESC"
-  PIDFILE=
-  for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
-    NAME=`echo $PIDFILE | cut -c18-`
+  for PIDFILE in `ls /run/openvpn/*.pid 2> /dev/null`; do
+    NAME=`echo $PIDFILE | cut -c14-`
     NAME=${NAME%%.pid}
     log_daemon_msg "  Soft-restarting VPN '$NAME'"
     kill -USR1 `cat $PIDFILE` || true
@@ -228,18 +231,15 @@ soft-restart)
 restart)
   shift
   $0 stop ${@}
-  sleep 1
   $0 start ${@}
   ;;
 cond-restart)
   log_action_begin_msg "Restarting $DESC"
-  PIDFILE=
-  for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
-    NAME=`echo $PIDFILE | cut -c18-`
+  for PIDFILE in `ls /run/openvpn/*.pid 2> /dev/null`; do
+    NAME=`echo $PIDFILE | cut -c14-`
     NAME=${NAME%%.pid}
     log_daemon_msg "  Stopping VPN '$NAME'"
     stop_vpn
-    sleep 1
     log_daemon_msg "  Restarting VPN '$NAME'"
     start_vpn
   done
@@ -286,9 +286,9 @@ status)
       fi
       if test "x$AUTOVPN" = "x1" ; then
         # If it is autostarted, then it contributes to global status
-        status_of_proc -p /var/run/openvpn.${NAME}.pid openvpn "VPN '${NAME}'" || GLOBAL_STATUS=1
+        status_of_proc -p /run/openvpn/${NAME}.pid openvpn "VPN '${NAME}'" || GLOBAL_STATUS=1
       else
-        status_of_proc -p /var/run/openvpn.${NAME}.pid openvpn "VPN '${NAME}' (non autostarted)" || true
+        status_of_proc -p /run/openvpn/${NAME}.pid openvpn "VPN '${NAME}' (non autostarted)" || true
       fi
     done
   else
@@ -299,7 +299,7 @@ status)
       NAME=$1
       if test -e $CONFIG_DIR/$NAME.conf ; then
         # Config exists
-        status_of_proc -p /var/run/openvpn.${NAME}.pid openvpn "VPN '${NAME}'" || GLOBAL_STATUS=1
+        status_of_proc -p /run/openvpn/${NAME}.pid openvpn "VPN '${NAME}'" || GLOBAL_STATUS=1
       else
         # Config does not exist
         log_warning_msg "VPN '$NAME': missing $CONFIG_DIR/$NAME.conf file !"
